config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :products 
     resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!
	  	

	  	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up,keys:[:firstname,:lastname])

   devise_parameter_sanitizer.permit(:account_update,keys:[:firstname,:lastname])
		
end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	@user = current_user
	@orders= @user.orders.paginate(page:params[:page], per_page:5)
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @user =current_user
    @product = Product.find(params[:product_id])
    @order = @product.orders.create(order_params)
    @quantity =(@product.quantity)-1
    @product_update = @product.update(quantity: @quantity)
    flash[:notice] = "order placed successfully"
    redirect_to cart_path

  end

    def order_params
      params.require(:order).permit(:quantity, :product_id, :user_id)
    end
    def index
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.paginate(page: params[:page],per_page:5)
  end

  def show
    @user = current_user
    @product =Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart/show.html.erb
<div class ="container">
	<% if !@orders.empty? %>
	<% @orders.each do |item| %>
	<div class ="row justify-content-md-center">
		<div class ="col-8 mt-4">
<div class ="cart text-center shadow mb-5 bg-white rounded">
<div class ="cart-body">
<h5 class="cart-title"><%= item.product.name%></h5>
<p class="cart-text"><%= item.quantity%></p>
<p class ="cart-body"><%= item.price%></p>
</div>
 
</div>

			</div>
			<% end %>
		</div>
		<div class="flickr_pagination">
			<%= will_paginate @orders, :container=> false>
		</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
  <% if @product.quantity !=0 %>
  <% if user_signed_in? %>
   <%= form_for([@product, @product.orders.build]) do |f| %>
    <%= f.number_field :quantity %>
    <%= f.number_field :product_id %>
    <%= f.number_field :user_id %>
    <%= f.submit %>

<% end %>
<% else %>
<%= link_to 'login to purchase', new_user_session_path %>
<% end %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Product</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <td><%= order.quantity %></td>
        <td><%= order.product_id %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/home.html.erb
<br>
<i>
<strong><center><h1 style="color:black">Welcome To The Clothing Store</h1></center></strong>
<center>
<h3 style="color:Black">|
    <%= link_to 'Collection', products_path %> |
 
 <%= link_to 'Wishlist', orders_path %> |
     <%= link_to 'Cart', orders_path %> |

</h3></center>
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 
</i>


                                 
                         

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
 <div class ="flickr_pagination mb-4">
<%= will_paginate @products, :container => false %>
  </div>s
<br>
<i>
<h1 style="color:violet;"> List of Products</h1>>
<h3>
<table bgcolor="pink">
  <thead>
    <tr style="color:blue">
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="4"></th>
    </tr>
  </thead>

    <% @products.each do |product| %>
        <td><%= product.name %></td> 
          <% if product.quantity != 0 %>
            <p>Quantity:<%=product.quantity %></p>
          <% else %>
          <p>out of stock</p>
    <% end %>
    <% link_to 'View Details',product_path %>
    <% end %>
  <div class ="flickr_pagination mb-4">
<%= will_paginate @products, :container => false %>
  </div>
    

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>